version: '2.1'
services:
    odoo:
        image: odoo:14.0
        depends_on:
            - db
            - elasticsearch
            - kibana
        ports:
            - "8069:8069"
        volumes:
            - odoo-data:/var/lib/odoo:rw,z
            - ./:/mnt/extra-addons:ro,z
        networks:
          - esnet
    db:
        image: docker.io/library/postgres:10.13
        environment:
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
            - POSTGRES_DB=postgres
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - db-data:/var/lib/postgresql/data/pgdata:rw,Z
        networks:
          - esnet
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
        container_name: elasticsearch
        environment:
          - cluster.name=docker-cluster
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        volumes:
          - esdata:/usr/share/elasticsearch/data
        ports:
          - "9200:9200"
        networks:
          - esnet

    kibana:
        image: docker.elastic.co/kibana/kibana:6.6.1
        container_name: kibana
        environment:
          - ./kibana.yml:/usr/share/kibana/config/kibana.yml
        ports:
          - "5601:5601"
        networks:
          - esnet
volumes:
    odoo-data:
    db-data:
    esdata:
      driver: local
networks:
  esnet:
    driver: bridge
